baseURL = "https://falicitas.github.io/"
locale = "zh-CN"
title = "Kinesis' blogs"
theme = "PaperMod"
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName  = "atom"

[params]
  ShowReadingTime = true
  defaultTheme = "auto"
  [params.homeInfoParams]
    Title = "Kinesis"
    Content = "个人博客"

[[menu.main]]
  name = "Posts"
  url  = "/posts/"
  weight = 1
[[menu.main]]
  name = "Tags"
  url  = "/tags/"
  weight = 2
[[menu.main]]
  name = "RSS"
  url  = "/atom.xml"
  weight = 3
